import { MigrationInterface, QueryRunner } from "typeorm";

export class default1663336918240 implements MigrationInterface {
    name = 'default1663336918240'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "teste"."cabecalho_doc_embarque" ("id" SERIAL NOT NULL, CONSTRAINT "PK_28ba9f33e098b1d74b2ea729dae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."vendedor" ("id" SERIAL NOT NULL, "perc_comissao" numeric(3,2), "validate" TIMESTAMP, "incluido_por" character varying(50) NOT NULL, "dt_inclusao" TIMESTAMP NOT NULL DEFAULT now(), "alterado_por" character varying(50) NOT NULL, "dt_alteracao" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a8111a025da487e8ad05afa6b79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."cliente_tipo_faturamento_enum" AS ENUM('Diário', 'Dezenal', 'Eventual', 'Semanal', 'Quinsenal', 'Mensal', 'Automático')`);
        await queryRunner.query(`CREATE TABLE "teste"."cliente" ("id" SERIAL NOT NULL, "cnpj_pag" character varying(14) NOT NULL, "dt_mov" TIMESTAMP NOT NULL, "inadimplente" boolean DEFAULT false, "calc_frt_maior" boolean DEFAULT false, "cobrar_icms" boolean DEFAULT false, "reter_iss" boolean DEFAULT false, "insentar_rctrc" boolean DEFAULT false, "resp_seguro" boolean DEFAULT false, "cnpj_seguradora" character varying(14), "nome_seguradora" character varying(100), "nr_apolice" character varying(30), "nr_averbacao" character varying(30), "max_assegurado" numeric DEFAULT '0', "dt_vencimento_ddr" TIMESTAMP, "tipo_faturamento" "teste"."cliente_tipo_faturamento_enum" DEFAULT 'Eventual', "redespachante_id" bigint, "vendedor_id" integer, "dt_cadastro" TIMESTAMP NOT NULL DEFAULT now(), "cadastrado_por" character varying(50) NOT NULL, "dt_Alteracao" TIMESTAMP NOT NULL DEFAULT now(), "alterador_por" character varying(50) NOT NULL, "pessoa_id" integer, CONSTRAINT "REL_88aec6333a4a24cee95e3e62e1" UNIQUE ("pessoa_id"), CONSTRAINT "PK_18990e8df6cf7fe71b9dc0f5f39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."banco" ("id" SERIAL NOT NULL, "banco" character varying(3) NOT NULL, "nome" character varying(50) NOT NULL, CONSTRAINT "UQ_cde56dead20a7dd5fcc34698537" UNIQUE ("banco"), CONSTRAINT "PK_8057583df0fc355378b537cb743" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."dados_bancarios_pag_tipo_conta_enum" AS ENUM('0', '1')`);
        await queryRunner.query(`CREATE TYPE "teste"."dados_bancarios_pag_tipo_chave_pix_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "teste"."dados_bancarios_pag" ("id" SERIAL NOT NULL, "tipo_conta" "teste"."dados_bancarios_pag_tipo_conta_enum" NOT NULL DEFAULT '0', "agencia_numero" character varying(10) NOT NULL, "agencia_digito" character varying(1) NOT NULL, "conta_numero" character varying(20) NOT NULL, "conta_digito" character varying(1) NOT NULL, "tipo_chave_pix" "teste"."dados_bancarios_pag_tipo_chave_pix_enum", "chave_pix" character varying(100), "banco_id" integer, "pessoa_id" integer, CONSTRAINT "PK_1d0b486aa938d3199853d17c95d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."motorista_estado_civil_enum" AS ENUM('0', '1', '2', '3', '4', '5')`);
        await queryRunner.query(`CREATE TYPE "teste"."motorista_carac_sexo_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TABLE "teste"."motorista" ("id" SERIAL NOT NULL, "estado_civil" "teste"."motorista_estado_civil_enum" NOT NULL DEFAULT '5', "cnh_numero" character varying(20) NOT NULL, "cnh_categoria" character varying(3) NOT NULL, "cnh_registro" character varying(20), "cnh_uf" character varying(2), "cnh_emissao" TIMESTAMP, "cnh_validade" TIMESTAMP, "cnh_data_primeira" TIMESTAMP, "cnh_codigo_seguranca" character varying(20), "exame_toxilogico_validade" TIMESTAMP, "seg_cartao" character varying(20), "seg_liberacao" character varying(20), "seg_liberacao_validade" TIMESTAMP, "seg_valor_assegurado" numeric(15,2), "seg_codido_sm" character varying(20), "carac_barba" character varying(50), "carac_cabelo" character varying(50), "carac_pelo" character varying(50), "carac_olhos" character varying(10), "carac_sexo" "teste"."motorista_carac_sexo_enum" NOT NULL DEFAULT '3', "carac_sinais" character varying(50), "carac_tatuagens" character varying(50), "carac_tipo_sanguineo" character varying(2), "carac_altura" numeric(3,2), "carac_peso" numeric(3,2), "ciot_cartao" character varying(20), "ciot_cartao_pedagio" character varying(20), "perc_comissao" character varying(20), "empresa_respostavel" character varying(20), "pessoa_id" integer, CONSTRAINT "UQ_193f6ba675839e7dd9410082611" UNIQUE ("cnh_numero"), CONSTRAINT "REL_e99b46712b103d0a7f56829971" UNIQUE ("pessoa_id"), CONSTRAINT "PK_ab94c3b7ad53a62d54b775a2a2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."tipo_carroceria" ("id" SERIAL NOT NULL, "carroceria" character varying(30) NOT NULL, CONSTRAINT "UQ_baf88a81da5c956709e3d00315c" UNIQUE ("carroceria"), CONSTRAINT "PK_5e396554023ad644d905d3bcf30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."tipo_combustivel" ("id" SERIAL NOT NULL, "tipo_combustivel" character varying(30) NOT NULL, CONSTRAINT "UQ_292aa95bac537e1b4bc16660297" UNIQUE ("tipo_combustivel"), CONSTRAINT "PK_ad4575bb9f73a3b8c2db4bd6ca2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."tipo_veiculo" ("id" SERIAL NOT NULL, "tipo_veiculo" character varying(30) NOT NULL, CONSTRAINT "UQ_51d9b6da688d0ab167ac8ff9553" UNIQUE ("tipo_veiculo"), CONSTRAINT "PK_d53551643507e31ef176227b768" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."veiculo_modelo" ("id" SERIAL NOT NULL, "modelo" character varying(50) NOT NULL, CONSTRAINT "UQ_454dada09f09b8a5db95ee996c1" UNIQUE ("modelo"), CONSTRAINT "PK_4098e0685d78bb12b703a06d319" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."veiculo_marca" ("id" SERIAL NOT NULL, "marca" character varying(50) NOT NULL, CONSTRAINT "UQ_f763f0b4cae9507c41a5715d1c1" UNIQUE ("marca"), CONSTRAINT "PK_374fa11546846339b8327f2ea72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."veiculo_vinculo_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TYPE "teste"."veiculo_favorecido_enum" AS ENUM('0', '1')`);
        await queryRunner.query(`CREATE TYPE "teste"."veiculo_tag_pedagio_enum" AS ENUM('0', '1', '2', '3', '4', '5', '6')`);
        await queryRunner.query(`CREATE TABLE "teste"."veiculo" ("id" SERIAL NOT NULL, "placa" character varying(9) NOT NULL, "qtd_eixos" integer, "ano_fabricacao" integer NOT NULL, "vinculo" "teste"."veiculo_vinculo_enum" NOT NULL, "favorecido" "teste"."veiculo_favorecido_enum" NOT NULL, "categoria_pedagio" character varying(100), "cor_cabine" character varying(20), "cor_carroceria" character varying(20), "seg_validade" TIMESTAMP, "cod_sm" character varying(20), "chassis" character varying(30), "numero_motor" character varying(30), "certificado" character varying(30), "renavam" character varying(30), "odometro" numeric(10,3), "data_licenciamento" TIMESTAMP, "apolice_vencimento" TIMESTAMP, "apolice_seguro" character varying(20), "tag_pedagio" "teste"."veiculo_tag_pedagio_enum" NOT NULL DEFAULT '6', "tipo_veiculo_id" integer, "tipo_combustivel_id" integer, "veiculo_marca_id" integer, "veiculo_modelo_id" integer, "cod_municipio" integer, "tipo_carroceria_id" integer, "proprietario_veiculo_id" integer, CONSTRAINT "UQ_a6a498ac4313a6bc4f8967c24d1" UNIQUE ("placa"), CONSTRAINT "REL_c66ad44168af0b16821e0296a2" UNIQUE ("veiculo_marca_id"), CONSTRAINT "REL_cb9262c97b65b05562912e82ee" UNIQUE ("veiculo_modelo_id"), CONSTRAINT "REL_1bcf51db645ae90d89d2039502" UNIQUE ("cod_municipio"), CONSTRAINT "PK_0fcc9d29b16ed347447f8f9356e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."proprietario_veiculo" ("id" SERIAL NOT NULL, "rntrc" character varying(9) NOT NULL, "validade_rntrc" TIMESTAMP NOT NULL, "ativo" boolean NOT NULL DEFAULT true, "reter_inss" boolean NOT NULL DEFAULT true, "reter_irpf" boolean NOT NULL DEFAULT true, "nis" character varying(20) NOT NULL, "nro_dependentes" integer NOT NULL DEFAULT '0', "com_contrato" boolean NOT NULL DEFAULT false, "pessoa_id" integer, CONSTRAINT "REL_4d78e80595e548eb0e1b45cf91" UNIQUE ("pessoa_id"), CONSTRAINT "PK_fe1321fac25092da5200827ac40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."telefone_tipo_enum" AS ENUM('Fixo', 'Celular', 'Outros')`);
        await queryRunner.query(`CREATE TABLE "teste"."telefone" ("id" SERIAL NOT NULL, "tipo" "teste"."telefone_tipo_enum" NOT NULL DEFAULT 'Fixo', "ddd" character varying(2) NOT NULL, "numero" character varying(20) NOT NULL, "contato" character varying(60), "pessoa_id" integer, CONSTRAINT "PK_6b27db34d6da7b23e8680a55fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "teste"."pessoa_tipo_contrib_enum" AS ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8')`);
        await queryRunner.query(`CREATE TABLE "teste"."pessoa" ("id" SERIAL NOT NULL, "cnpj_cpf" character varying NOT NULL, "razao_social" character varying(100) NOT NULL, "fantasia" character varying(100), "ie_rg" character varying(20), "dt_nasc" TIMESTAMP, "cod_contabil" character varying(20), "ativo" boolean NOT NULL DEFAULT true, "dt_cadastro" TIMESTAMP NOT NULL DEFAULT now(), "cadastrado_por" character varying(50) NOT NULL, "dt_Alteracao" TIMESTAMP NOT NULL DEFAULT now(), "alterador_por" character varying(50) NOT NULL, "cat_pessoa" character varying(200) array NOT NULL, "tipo_contrib" "teste"."pessoa_tipo_contrib_enum" NOT NULL, "email" character varying(100), CONSTRAINT "PK_bb879ac36994545a5a917a09ba5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f492b8f7c59d977d0d14c47402" ON "teste"."pessoa" ("cnpj_cpf") `);
        await queryRunner.query(`CREATE TABLE "teste"."tipo_endereco" ("id" SERIAL NOT NULL, "tipo" character varying(50) NOT NULL, CONSTRAINT "PK_41739b77a8dfe760823d740b3bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."endereco" ("id" SERIAL NOT NULL, "logradouro" character varying(100), "numero" character varying(20), "complenento" character varying(50), "bairro" character varying(60), "cep" character varying(8), "latitude" character varying(20), "longitude" character varying(20), "cod_municipio" integer, "pessoa_id" integer, "tipo_endereco" integer, CONSTRAINT "PK_2a6880f71a7f8d1c677bb2a32a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."pais" ("id" integer NOT NULL, "nome_pais" character varying(50) NOT NULL, CONSTRAINT "PK_a362c5bbbefe39c9187406b1917" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."estado" ("id" integer NOT NULL, "UF" character varying(2) NOT NULL, "nome" character varying(50) NOT NULL, "cod_pais" integer, CONSTRAINT "PK_be2ef64a21d36522aa1ecb24886" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste"."cidade" ("cod_municipio" integer NOT NULL, "cidade" character varying(100) NOT NULL, "al_iss" numeric DEFAULT '0', "padrao_nfse" character varying(20), "cod_uf" integer, CONSTRAINT "PK_3457bbeaeda680b5c725066e877" PRIMARY KEY ("cod_municipio"))`);
        await queryRunner.query(`CREATE TABLE "teste"."empresa" ("id" SERIAL NOT NULL, "cnpj" character varying(14) NOT NULL, "unidade" character varying(3) NOT NULL, "ativo" boolean NOT NULL DEFAULT true, "insc_estadual" character varying(20), "logradouro" character varying(100) NOT NULL, "numero" character varying(20) NOT NULL, CONSTRAINT "PK_bee78e8f1760ccf9cff402118a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_08c5aedcfa88ad70b503406e34" ON "teste"."empresa" ("cnpj", "unidade") `);
        await queryRunner.query(`CREATE TABLE "teste"."veiculo_marca_modelos_veiculo_modelo" ("veiculoMarcaId" integer NOT NULL, "veiculoModeloId" integer NOT NULL, CONSTRAINT "PK_1a163b9e534b40f8f2ffec18a44" PRIMARY KEY ("veiculoMarcaId", "veiculoModeloId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90ca37533d5d38c4a2ef8757c3" ON "teste"."veiculo_marca_modelos_veiculo_modelo" ("veiculoMarcaId") `);
        await queryRunner.query(`CREATE INDEX "IDX_15a16c8dca4618609885e5bfea" ON "teste"."veiculo_marca_modelos_veiculo_modelo" ("veiculoModeloId") `);
        await queryRunner.query(`ALTER TABLE "teste"."cliente" ADD CONSTRAINT "FK_88aec6333a4a24cee95e3e62e18" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."cliente" ADD CONSTRAINT "FK_9f1853243cb97ee349d40627c83" FOREIGN KEY ("vendedor_id") REFERENCES "teste"."vendedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."dados_bancarios_pag" ADD CONSTRAINT "FK_6fdc1cfb0b4acdee7ed9025984b" FOREIGN KEY ("banco_id") REFERENCES "teste"."banco"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."dados_bancarios_pag" ADD CONSTRAINT "FK_851639b518cf7878b8f91e1287d" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."motorista" ADD CONSTRAINT "FK_e99b46712b103d0a7f568299712" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_2c3ab27efdc468580dfbb04124f" FOREIGN KEY ("tipo_veiculo_id") REFERENCES "teste"."tipo_veiculo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_ece1e6234c8cda4f6a3cc367acc" FOREIGN KEY ("tipo_combustivel_id") REFERENCES "teste"."tipo_combustivel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_c66ad44168af0b16821e0296a24" FOREIGN KEY ("veiculo_marca_id") REFERENCES "teste"."veiculo_marca"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_cb9262c97b65b05562912e82ee4" FOREIGN KEY ("veiculo_modelo_id") REFERENCES "teste"."veiculo_modelo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_1bcf51db645ae90d89d20395026" FOREIGN KEY ("cod_municipio") REFERENCES "teste"."cidade"("cod_municipio") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_5feb7b6294356e29d7a0dfddc29" FOREIGN KEY ("tipo_carroceria_id") REFERENCES "teste"."tipo_carroceria"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" ADD CONSTRAINT "FK_76763482acc21b5bf22b473036c" FOREIGN KEY ("proprietario_veiculo_id") REFERENCES "teste"."proprietario_veiculo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."proprietario_veiculo" ADD CONSTRAINT "FK_4d78e80595e548eb0e1b45cf918" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."telefone" ADD CONSTRAINT "FK_d3681875be7af919619f805fa96" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" ADD CONSTRAINT "FK_a724f11840e172583673c36aaf5" FOREIGN KEY ("cod_municipio") REFERENCES "teste"."cidade"("cod_municipio") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" ADD CONSTRAINT "FK_3bfbc39422af5aeae0e0697f772" FOREIGN KEY ("pessoa_id") REFERENCES "teste"."pessoa"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" ADD CONSTRAINT "FK_fbc3cb174dc39aa58e84b2e49b7" FOREIGN KEY ("tipo_endereco") REFERENCES "teste"."tipo_endereco"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teste"."estado" ADD CONSTRAINT "FK_0328355c77858ba69a358d412f2" FOREIGN KEY ("cod_pais") REFERENCES "teste"."pais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."cidade" ADD CONSTRAINT "FK_044348e9f4ebb0134203f5e1bf7" FOREIGN KEY ("cod_uf") REFERENCES "teste"."estado"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo_marca_modelos_veiculo_modelo" ADD CONSTRAINT "FK_90ca37533d5d38c4a2ef8757c38" FOREIGN KEY ("veiculoMarcaId") REFERENCES "teste"."veiculo_marca"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo_marca_modelos_veiculo_modelo" ADD CONSTRAINT "FK_15a16c8dca4618609885e5bfea0" FOREIGN KEY ("veiculoModeloId") REFERENCES "teste"."veiculo_modelo"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "teste"."veiculo_marca_modelos_veiculo_modelo" DROP CONSTRAINT "FK_15a16c8dca4618609885e5bfea0"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo_marca_modelos_veiculo_modelo" DROP CONSTRAINT "FK_90ca37533d5d38c4a2ef8757c38"`);
        await queryRunner.query(`ALTER TABLE "teste"."cidade" DROP CONSTRAINT "FK_044348e9f4ebb0134203f5e1bf7"`);
        await queryRunner.query(`ALTER TABLE "teste"."estado" DROP CONSTRAINT "FK_0328355c77858ba69a358d412f2"`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" DROP CONSTRAINT "FK_fbc3cb174dc39aa58e84b2e49b7"`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" DROP CONSTRAINT "FK_3bfbc39422af5aeae0e0697f772"`);
        await queryRunner.query(`ALTER TABLE "teste"."endereco" DROP CONSTRAINT "FK_a724f11840e172583673c36aaf5"`);
        await queryRunner.query(`ALTER TABLE "teste"."telefone" DROP CONSTRAINT "FK_d3681875be7af919619f805fa96"`);
        await queryRunner.query(`ALTER TABLE "teste"."proprietario_veiculo" DROP CONSTRAINT "FK_4d78e80595e548eb0e1b45cf918"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_76763482acc21b5bf22b473036c"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_5feb7b6294356e29d7a0dfddc29"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_1bcf51db645ae90d89d20395026"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_cb9262c97b65b05562912e82ee4"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_c66ad44168af0b16821e0296a24"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_ece1e6234c8cda4f6a3cc367acc"`);
        await queryRunner.query(`ALTER TABLE "teste"."veiculo" DROP CONSTRAINT "FK_2c3ab27efdc468580dfbb04124f"`);
        await queryRunner.query(`ALTER TABLE "teste"."motorista" DROP CONSTRAINT "FK_e99b46712b103d0a7f568299712"`);
        await queryRunner.query(`ALTER TABLE "teste"."dados_bancarios_pag" DROP CONSTRAINT "FK_851639b518cf7878b8f91e1287d"`);
        await queryRunner.query(`ALTER TABLE "teste"."dados_bancarios_pag" DROP CONSTRAINT "FK_6fdc1cfb0b4acdee7ed9025984b"`);
        await queryRunner.query(`ALTER TABLE "teste"."cliente" DROP CONSTRAINT "FK_9f1853243cb97ee349d40627c83"`);
        await queryRunner.query(`ALTER TABLE "teste"."cliente" DROP CONSTRAINT "FK_88aec6333a4a24cee95e3e62e18"`);
        await queryRunner.query(`DROP INDEX "teste"."IDX_15a16c8dca4618609885e5bfea"`);
        await queryRunner.query(`DROP INDEX "teste"."IDX_90ca37533d5d38c4a2ef8757c3"`);
        await queryRunner.query(`DROP TABLE "teste"."veiculo_marca_modelos_veiculo_modelo"`);
        await queryRunner.query(`DROP INDEX "teste"."IDX_08c5aedcfa88ad70b503406e34"`);
        await queryRunner.query(`DROP TABLE "teste"."empresa"`);
        await queryRunner.query(`DROP TABLE "teste"."cidade"`);
        await queryRunner.query(`DROP TABLE "teste"."estado"`);
        await queryRunner.query(`DROP TABLE "teste"."pais"`);
        await queryRunner.query(`DROP TABLE "teste"."endereco"`);
        await queryRunner.query(`DROP TABLE "teste"."tipo_endereco"`);
        await queryRunner.query(`DROP INDEX "teste"."IDX_f492b8f7c59d977d0d14c47402"`);
        await queryRunner.query(`DROP TABLE "teste"."pessoa"`);
        await queryRunner.query(`DROP TYPE "teste"."pessoa_tipo_contrib_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."telefone"`);
        await queryRunner.query(`DROP TYPE "teste"."telefone_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."proprietario_veiculo"`);
        await queryRunner.query(`DROP TABLE "teste"."veiculo"`);
        await queryRunner.query(`DROP TYPE "teste"."veiculo_tag_pedagio_enum"`);
        await queryRunner.query(`DROP TYPE "teste"."veiculo_favorecido_enum"`);
        await queryRunner.query(`DROP TYPE "teste"."veiculo_vinculo_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."veiculo_marca"`);
        await queryRunner.query(`DROP TABLE "teste"."veiculo_modelo"`);
        await queryRunner.query(`DROP TABLE "teste"."tipo_veiculo"`);
        await queryRunner.query(`DROP TABLE "teste"."tipo_combustivel"`);
        await queryRunner.query(`DROP TABLE "teste"."tipo_carroceria"`);
        await queryRunner.query(`DROP TABLE "teste"."motorista"`);
        await queryRunner.query(`DROP TYPE "teste"."motorista_carac_sexo_enum"`);
        await queryRunner.query(`DROP TYPE "teste"."motorista_estado_civil_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."dados_bancarios_pag"`);
        await queryRunner.query(`DROP TYPE "teste"."dados_bancarios_pag_tipo_chave_pix_enum"`);
        await queryRunner.query(`DROP TYPE "teste"."dados_bancarios_pag_tipo_conta_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."banco"`);
        await queryRunner.query(`DROP TABLE "teste"."cliente"`);
        await queryRunner.query(`DROP TYPE "teste"."cliente_tipo_faturamento_enum"`);
        await queryRunner.query(`DROP TABLE "teste"."vendedor"`);
        await queryRunner.query(`DROP TABLE "teste"."cabecalho_doc_embarque"`);
    }

}
